server:
  service:
    type: NodePort
    nodePortHttp: 30004
    nodePortHttps: 30005

# --- helm-secrets 통합 ---
repoServer:
  # Age private key를 환경변수로 주입
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /helm-secrets-private-keys/key.txt
    - name: HELM_PLUGINS
      value: /custom-tools/helm-plugins/
    - name: HELM_SECRETS_HELM_PATH
      value: /usr/local/bin/helm
    - name: HELM_SECRETS_SOPS_PATH
      value: /custom-tools/sops
    - name: HELM_SECRETS_BACKEND
      value: sops
    - name: HELM_SECRETS_WRAPPER_ENABLED
      value: "true"
    - name: HELM_SECRETS_VALUES_ALLOW_ABSOLUTE_PATH
      value: "true"
    - name: PATH # sops가 age를 찾는 경로
      value: /custom-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  # Init container: helm-secrets + sops + age 설치
  initContainers:
    - name: install-helm-secrets
      image: alpine:3.18
      command:
        - sh
        - -c
        - |
          set -e
          # age 설치
          apk add --no-cache age
          cp /usr/bin/age /custom-tools/age
          cp /usr/bin/age-keygen /custom-tools/age-keygen
          chmod +x /custom-tools/age /custom-tools/age-keygen

          # SOPS 설치
          wget -qO /custom-tools/sops https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.linux.amd64
          chmod +x /custom-tools/sops

          # helm-secrets 플러그인 설치
          mkdir -p /custom-tools/helm-plugins
          wget -qO- https://github.com/jkroepke/helm-secrets/releases/download/v4.6.10/helm-secrets.tar.gz | tar -C /custom-tools/helm-plugins -xzf-
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools

  # Volume mounts
  volumeMounts:
    - name: custom-tools
      mountPath: /custom-tools
    - name: helm-secrets-private-keys
      mountPath: /helm-secrets-private-keys/
      readOnly: true

  # Volumes
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: helm-secrets-private-keys
      secret:
        secretName: helm-secrets-private-keys

# ArgoCD ConfigMap 설정
configs:
  cm:
    # helm-secrets 스킴 허용
    helm.valuesFileSchemes: >-
      secrets+gpg-import, secrets+gpg-import-kubernetes,
      secrets+age-import, secrets+age-import-kubernetes,
      secrets, secrets+literal,
      https
