auth:
  rootPassword: ENC[AES256_GCM,data:tc8HNVgI4+ElfE8=,iv:x+Ocod9iozjABv7OlRUSI9FtU2CnHYnAtH+Pbzz7Lxs=,tag:JroWT4iTZ6q7yNdFk1e6Hw==,type:str]
  username: ENC[AES256_GCM,data:BD2tuW2uEw==,iv:vrjjOELFfAIQLbN1tQ1YmTH81pPCwcfWhuq2EY3xNRk=,tag:uUZKyRvBIZzxOTHBLQSJuw==,type:str]
  password: ENC[AES256_GCM,data:gUssdHoTnLXd6zc5,iv:LjrmnTDc1bJWRB3o4odrFQVuI5kExLg2KhDADTyYMPw=,tag:/8crGuInwyLBQ8kE8V7G+w==,type:str]
sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eXU2UFBsZUNwMEtBNnh5
        UlljWUZ5OUNHa1Z3ME03dk5ZcFdqWFdzZG5NClV0N0NZUHl5MkNpUXJGOW9WdjhT
        QXg1ajlvU3I1TUlua3E0NkNlRTNXRGsKLS0tIHZ1aFBoTVhMVkMwS2dVa1JUZ0x2
        ZFFaaHQzVlE3S1d0Ti9iTmQxdDhJcjAKKmZ4FditBpVRfLYREklw7IBpZbBLEOPb
        JIs2bRUAMkNeeUZzBF8UiOkj8HnYvnq0VKT9fR2BBmvJPdB4x/5Img==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T01:33:58Z"
  mac: ENC[AES256_GCM,data:pd/oUmYtsEwbOzvSzaQLWaRILY0kAcHLXBXsLE9t8qZTu8sVCZP8ESFpYcEO5uB5K2QsvOiilwAzQOp4IqsA8o+hYwiHcC0bmYTCaSk4o10Y337fdirEs8btIvbTJzaK7eY+qAQp4FLG9HWa9a9133ZzPimRIU7xW9/9ehoQ5vE=,iv:bnpgdtNZDYRuzX4bEVENIK/J6s0nTNEFS6I2vq2KkwE=,tag:JtkSUIaC9rkvp3rWLterWA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
