annotations:
  category: Database
  # TODO 무료 지원이 종료된 bitnami 대신 이미지 변경 필요
  images: |
    - name: mysql
      image: docker.io/bitnamilegacy/mysql:9.4.0-debian-12-r1
    - name: mysqld-exporter
      image: docker.io/bitnamilegacy/mysqld-exporter:0.17.2-debian-12-r16
    - name: os-shell
      image: docker.io/bitnamilegacy/os-shell:12-debian-12-r50
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 9.4.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: MySQL is a fast, reliable, scalable, and easy to use open source relational
  database system. Designed to handle mission-critical, heavy-load production applications.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
  - mysql
  - database
  - sql
  - cluster
  - high availability
maintainers:
  - name: Broadcom, Inc. All Rights Reserved.
    url: https://github.com/bitnami/charts
name: mysql
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/mysql
version: 14.0.3
