secrets:
  jwtSecret: ENC[AES256_GCM,data:h2jwQ6PRMoQrBtV6xT2FSDTSzrLSCYLWDYz++x3BKJA=,iv:kSmpAuyCwG45oxRXLISULsdWucKthew1eS5lSI3YJ/E=,tag:y8TcdnBYuBIgWikn9fBUOg==,type:str]
sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUkxSaDVrVVZObjQxZllm
        REpicUNobFNIZlFsUmFUNzZ3ajlhZnVabHdvCmJ1U2RmVkY4OE43MmxSR25ySHVL
        Slh1ZWZjdklVRkV0NStWM0tnbkV6bUUKLS0tIHBsV3MxWnROUGJTS2hoN01lRW10
        MklPUE8wN1V1VEx4K0xPajYweVdQT0EKUbLG5FPXTvOBqC0OmLicCgm6f0CC8MyF
        D+36BRiIXelrCit/2iKrk5/EXGQUDnog8wjLiWsKKKYfpNMib2bHRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-14T09:51:03Z"
  mac: ENC[AES256_GCM,data:l8lTEvn7Ryg5mV0T0jhBL0EEJSi6u21LVsRPg21UUp3SXS99ocsEtQyfJZlEUoKCSJ+wNYKOMXDgrGGvlVG68Eo6HzTkYrIsnSts2SOneWRI6tCIdr/obNFcFjU1nDRkIThhjWgQ3sk7Nlz5P0QgsNJ6XVPq2IQRCG0damZp/Ss=,iv:79iMnvzdcvflDsWGFKDvRrUIjZDartJOK7AxIcDfm8A=,tag:TqbnlTlioQHf5WfSOYC8og==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
