---
- name: Install k3s
  hosts: all
  become: true
  tasks:
    - name: Check if k3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_exists

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      when: not k3s_exists.stat.exists

    - name: Wait for k3s to be ready
      wait_for:
        port: 6443
        host: localhost
        delay: 10
        timeout: 120

    - name: Check k3s status
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Get nodes
      shell: kubectl get nodes
      register: nodes_output

    - name: Display nodes
      debug:
        msg: "{{ nodes_output.stdout_lines }}"
