---
- name: Install k3s
  hosts: all
  become: true
  tasks:
    - name: Check if k3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_exists

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      when: not k3s_exists.stat.exists

    - name: Wait for k3s to be ready
      wait_for:
        port: 6443
        host: localhost
        delay: 10
        timeout: 120

    - name: Check k3s status
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Create .kube directory for user
      file:
        path: /home/bannote/.kube
        state: directory
        owner: bannote
        group: bannote
        mode: "0755"

    - name: Copy kubeconfig to user home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/bannote/.kube/config
        owner: bannote
        group: bannote
        mode: "0644"
        remote_src: yes

    - name: Set KUBECONFIG environment variable in .bashrc
      lineinfile:
        path: /home/bannote/.bashrc
        line: "export KUBECONFIG=$HOME/.kube/config"
        create: yes
        owner: bannote
        group: bannote
        mode: "0644"

    - name: Configure Traefik to use node ports 30080 and 30443
      copy:
        dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
        content: |
          apiVersion: helm.cattle.io/v1
          kind: HelmChartConfig
          metadata:
            name: traefik
            namespace: kube-system
          spec:
            valuesContent: |-
              additionalArguments:
                - "--api"
                - "--api.dashboard=true"
                - "--api.insecure=true"
              ports:
                web:
                  port: 8000
                  exposedPort: 80
                  nodePort: 30080
                websecure:
                  port: 8443
                  exposedPort: 443
                  nodePort: 30443
                traefik:
                  port: 9000
                  expose:
                    default: true
                  exposedPort: 9000
                  nodePort: 30000
              service:
                type: NodePort
        mode: "0644"

    - name: Wait for Traefik to restart with new config
      pause:
        seconds: 30

    - name: Get nodes (as user)
      shell: kubectl get nodes
      become: false
      become_user: bannote
      environment:
        KUBECONFIG: /home/bannote/.kube/config
      register: nodes_output

    - name: Display nodes
      debug:
        msg: "{{ nodes_output.stdout_lines }}"
