---
- name: Install k3s
  hosts: all
  become: true
  tasks:
    - name: Check if k3s is already installed
      stat:
        path: /usr/local/bin/k3s
      register: k3s_exists

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      when: not k3s_exists.stat.exists

    - name: Wait for k3s to be ready
      wait_for:
        port: 6443
        host: localhost
        delay: 10
        timeout: 120

    - name: Check k3s status
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Create .kube directory for user
      file:
        path: /home/bannote/.kube
        state: directory
        owner: bannote
        group: bannote
        mode: "0755"

    - name: Copy kubeconfig to user home
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/bannote/.kube/config
        owner: bannote
        group: bannote
        mode: "0644"
        remote_src: yes

    - name: Set KUBECONFIG environment variable in .bashrc
      lineinfile:
        path: /home/bannote/.bashrc
        line: "export KUBECONFIG=$HOME/.kube/config"
        create: yes
        owner: bannote
        group: bannote
        mode: "0644"

    - name: Get nodes (as user)
      shell: kubectl get nodes
      become: false
      become_user: bannote
      environment:
        KUBECONFIG: /home/bannote/.kube/config
      register: nodes_output

    - name: Display nodes
      debug:
        msg: "{{ nodes_output.stdout_lines }}"
