---
- name: Install Helm
  hosts: all
  become: true
  tasks:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "0700"

    - name: Install Helm
      shell: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Verify Helm installation
      command: helm version
      register: helm_version
      changed_when: false

    - name: Display Helm version
      debug:
        msg: "{{ helm_version.stdout }}"

    - name: Install age (for SOPS encryption)
      apt:
        name: age
        state: present
        update_cache: yes

    - name: Install SOPS
      get_url:
        url: https://github.com/getsops/sops/releases/download/v3.9.3/sops-v3.9.3.linux.amd64
        dest: /usr/local/bin/sops
        mode: "0755"

    - name: Verify SOPS installation
      command: sops --version
      register: sops_version
      changed_when: false

    - name: Display SOPS version
      debug:
        msg: "{{ sops_version.stdout }}"

    - name: Create SOPS age key directory
      file:
        path: /home/bannote/.config/sops/age
        state: directory
        owner: bannote
        group: bannote
        mode: "0755"
      become: false

    - name: Install helm-secrets plugin
      shell: |
        if ! helm plugin list | grep -q "secrets"; then
          helm plugin install https://github.com/jkroepke/helm-secrets --version v4.6.10
        fi
      become: false
      become_user: bannote
      register: helm_secrets_install

    - name: Display helm-secrets installation result
      debug:
        msg: "{{ helm_secrets_install.stdout }}"

    - name: Verify helm-secrets plugin
      command: helm plugin list
      become: false
      become_user: bannote
      register: helm_plugins
      changed_when: false

    - name: Display installed Helm plugins
      debug:
        msg: "{{ helm_plugins.stdout_lines }}"
