auth:
  rootPassword: ENC[AES256_GCM,data:XQuiKCWBW4+aKbQ=,iv:BuqwFBjV4kZndMPh00zE40beFfhVmajvLK7eZXK2YHs=,tag:Iu8g6Y2v9lu3l+1cGHnr2g==,type:str]
  username: ENC[AES256_GCM,data:4kH4fXGwbg==,iv:JRNl+ekg58QsD8+ZGhdHpTBXiiKuGSpkvlXuASMnMC0=,tag:GhFLGPL2wX2qIED9cnPNVA==,type:str]
  password: ENC[AES256_GCM,data:Re0O6yxC5k4tSanm,iv:80HvcB2jKsf4412Z5ZQeHKKfr6jAlkH0PbtXsqYd9E4=,tag:UttcbERuGep8B+y8IA4PFw==,type:str]
sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVThudzhnN2xFK0cyVEtw
        L21VWXJPendtQldoaHJTTDVUQzNmS1M5R1IwCkd6NDhjU0pSV0pPcElSeTJsQ09p
        elZFZTJkUTN4d2loYXhJTVpYY05IdjQKLS0tIDFBWk1SNnBEc1FibWREVXUyVVR3
        KzNUa0Z0R1lSbXdzdjU1dzBqNEdzU2sKlICWoATjh6c+opeFoLeNUU4FXp2eI9Ry
        AS1OiztFiI13eTC/xs0cCSl6Ohbr3LlrBklwLYECCB4TASSXT1vA7A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-31T04:42:14Z"
  mac: ENC[AES256_GCM,data:beMFFYkO4i1Wjbyty+ZE1rO/f7cax87ESnSszXi2nBnG9rS5WPKS9vSKSUe8JP3ec9uuV1sVxGuWv84BVbEuGMzqZoVKZSwbaqMNKq2ZHWniLfhjR7nALaKOTZ9LZq2QUDO7GxKv8Zea58aTrNRVLTZGicZH7vn6BUA3Psb779M=,iv:6r+2u2jSsp91X3bWZzLhOTHxUUENM8CNGaOLHY6gNTQ=,tag:zPVSovnU0mj5eXmay7ySXA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
