configs:
  secret:
    argocdServerAdminPassword: ENC[AES256_GCM,data:iMt/mA==,iv:k8L7FUGVjabwn5Dam7tw7ermIRNkvjXCbJDZ7YdcZws=,tag:mSLa2uZWAdR8acZMx7eO5Q==,type:str]
sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU3YxclpMT1VNWDkzY3I0
        UGI5M3RESWFlMkVBRlc4Z1VsOFdxQ0pMYnlNCmpaTCtZS0hNUWQ3N2lYenV1UGZ3
        MHJYMkpQR1hqekVmWjBUTWk5MFgwbzAKLS0tIGR2MXlJZFBaeXc4M3hQQXFhTXJq
        NTlyT3d6R25JczViVHV1SjZ4b1ZzR2cKG8Cpey0t1jyFUxYU+E6s/zJKQ61RjEmG
        e9wdbHzSLRLn7uWF2UejWtTuyFanOEo1rIc0IdlmK8VOefwKDZkuKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-04T12:56:57Z"
  mac: ENC[AES256_GCM,data:pz4bVVtgJ6HlB41YkviaiNGGhvVlxnik8T5+pxLKzoCMZJr+VYf/lrKVb8W+45fmLVuDENmAmW2RPfi/EyVdK1Unn/6iHQZMiFbsBHMdQ+AcQSlxd9QbOYpxtz+JGjeSzokoFJWApOVTU5Oqbs84UVfwwFnqxUTgeEA4UqvBpaw=,iv:+pwjnAMfmg9Xupkw0v+pS+ut7oZ95siYIXAoobxm04g=,tag:lRef1YGX1XXaIEMbez/Cdw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
