name: Deploy LXD Infrastructure

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # 테라폼 설치
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # LXD 상태 확인 (미리 설치 후 lxd 그룹에 추가 필요)
      - name: Check LXD availability
        run: |
          echo "Checking if LXD is available..."
          if ! command -v lxc &> /dev/null; then
            echo "❌ LXD not found. Please install LXD on the runner server:"
            exit 1
          fi

          echo "✅ LXD found. Testing access..."
          lxc version
          lxc list
        shell: bash

      - name: Set Terraform branch variable
        id: set_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENV=main" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          fi

      - name: Terraform Apply
        working-directory: ./lxd-infra
        run: |
          terraform init
          terraform apply -auto-approve -var="environment=${{ env.ENV }}"
