adminUser: ENC[AES256_GCM,data:bDNo9vE=,iv:8Z6N48XLRTrGTulOSCkQinkicx8K4EN1PJpw/Lf2XK4=,tag:/hYd3PNjYfu1UjIYRLHaCA==,type:str]
adminPassword: ENC[AES256_GCM,data:YH1HZg==,iv:fne/ajbQIEwf2AmdA2TXxZXzEF09fIyJjDhkHOpORvs=,tag://7uPGc5s7ch6jNLARLfKw==,type:str]
sops:
  age:
    - recipient: age1qtuhjevdztafh9rpu6fqnpzercgn86c8mfrf4r0vw6cdgh6kvs0qyma2g5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVGs0aGEzZHh5MmVjREw2
        VlUrNGRjdy9OYm0yRHhCd21WR01iaTJ1ZlM0CnRuQzZtL3pnckpXL2tZTmZTS2Vj
        b25ZU2NqcFpmRjlZUDZxN1k4SG1CZ1UKLS0tIFVENlk1STFpYlo4dUUrMjlpNWtQ
        ejRNMmwzSnFrUGFiSmtFRFVwU292clkKdOQ6w5/4Y423rf9EdxugeRtKmUTKv2iz
        CJl1DuJOz9hm5ddRJeK1WVFhLreyfLwnZx1ufDgVKsOJuLFHrn4jDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-05T13:33:36Z"
  mac: ENC[AES256_GCM,data:EVynCKbWwU/GouvVxmH64U8LnwbEsnAmKw/1Uab830BmaUHwV5WgW2/RwcIZdrbfLjFHM/0zzzHwO7A1tIn0a5fKYDV6wep5pDzIEp+6Wg1ktiaqU3/DjReKa6+E5ytTM/kb1ZWfecb1lZXMpfVlNJybT86yyU27xUUKI7DRrtY=,iv:hprENPHRUoqdZFM/PrWVhVHF43ilqSzfzd0fUFUsNKM=,tag:VIoEhjo5ifwuUxBlcU1mdA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
